// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhx6rGFwiDuj49OF4qE4qW3haNW5yj50',
    appId: '1:482575205002:web:98c5cd4392107716ad6373',
    messagingSenderId: '482575205002',
    projectId: 'abiding-triode-442911-b8',
    authDomain: 'abiding-triode-442911-b8.firebaseapp.com',
    databaseURL: 'https://abiding-triode-442911-b8-default-rtdb.firebaseio.com',
    storageBucket: 'abiding-triode-442911-b8.firebasestorage.app',
    measurementId: 'G-5J3VBYX3T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8JxjnabTdVBbgLpD_ej5L5MVoyw04wvk',
    appId: '1:482575205002:android:7417751ae341b6edad6373',
    messagingSenderId: '482575205002',
    projectId: 'abiding-triode-442911-b8',
    databaseURL: 'https://abiding-triode-442911-b8-default-rtdb.firebaseio.com',
    storageBucket: 'abiding-triode-442911-b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3Gt-nnBIw0MxMAl8GC0PUEsl6ZkcbeI',
    appId: '1:482575205002:ios:5cb66d3a99ddf5b4ad6373',
    messagingSenderId: '482575205002',
    projectId: 'abiding-triode-442911-b8',
    databaseURL: 'https://abiding-triode-442911-b8-default-rtdb.firebaseio.com',
    storageBucket: 'abiding-triode-442911-b8.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );
}
